### ISSUE TITLE
tcii18n should be installable as requirement

### ISSUE THREAD

**Issue by vinyll** [anthropedia/tci-i18n#3]
we should be able to install this project as a 3rd party:

     pip install -e git+https://github.com/anthropedia/tci-tcii18n.git#egg=tci-i18n

in order to do this in an external project:

```
from tcii18n import Translator

translator = Translator('my_file.csv')
translator.translate('My string')
```

And the readme should provide an example like this and install instructions.

See https://github.com/anthropedia/tci-stats that may be a source example.

**Comment by Ydrasil** [comment]
@vinyll Does a readme is sufficient for installing this project as a 3rd party or it still something else to do ?

**Comment by vinyll** [comment]
A readme is not a magic file. A _setup.py_ is ;)

**Comment by Ydrasil** [comment]
This issue have to be closed, _setup.py_ file exist :)
